# -*- coding: utf-8 -*-
"""Dự án ML: Phân loại Titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fchJJYixzJrIB0ngobCw6H7H4mHriOJc

**Dự đoán khả năng sống sót của hành khách trên tàu Titanic.**

bài toán **Phân loại (Classification)**: Dựa trên thông tin đầu vào (tuổi, giới tính, hạng vé...bla bla), máy tính sẽ dự đoán hành khách đó "Sống sót" (1) hay "Không sống sót" (0).

Sử dụng ngôn ngữ **Python** và thư viện **Scikit-learn**.


### Tổng quan dự án ML này

1. **Mục tiêu:** Dự đoán hành khách sống hay chết.
2. **Dữ liệu:** Titanic Dataset (trên Kaggle).
3. **Mô hình:** Random Forest

### Bước 1: Thu thập & Khám phá dữ liệu
"""

# Import các thư viện cần thiết
import pandas as pd
import seaborn as sns # Dùngđể lấy data mẫu nhannh
import matplotlib.pyplot as plt

# 1. Thu thập dữ liệu
#tải bộ dữ liệu titanic trong thư viện seaborn
df = sns.load_dataset('titanic')

# Xem5 dòng đầu tiên
print("Dữ liệu thô ban đầu:")
print(df.head())

# Kiểm tra thông tin sơ sơ (số dòng, kdl, dữ liệu bị thiếu)
print("\nThông tin dữ liệu:")
print(df.info())

"""---

### Bước 2: Làm sạch & Xử lý dữ liệu (Data Cleaning & Preprocessing)

Máy tính không hiểu chữ (như "male", "female") và không tính toán được trên ô trống (NaN). Nếu bạn đưa dữ liệu rác vào, mô hình sẽ trả ra kết quả rác (**Garbage In, Garbage Out**).

**Vấn đề cần xử lý:**

1. **Missing Values (Dữ liệu thiếu):** Cột `age` (tuổi) và `embarked` (cảng lên tàu) bị thiếu.
2. **Categorical Data (Dữ liệu dạng chữ):** `sex`, `embarked` cần chuyển thành số.
3. **Redundant Data (Dữ liệu thừa):** Các cột như `deck` (quá nhiều missing), `embark_town` (trùng lặp) không giúp ích nhiều.
"""

# XỬ LÝ DỮ LIỆU THIẾU

# Điền tuổi bị thiếu bằng giá trị trung vị (Median) của cả cột
# Tại sao dùng Median??? Vì nếu có ai đó 100 tuổi, dùng Mean (tbc) sẽ bị sai lệch.
df['age'] = df['age'].fillna(df['age'].median())

# Điền cảng lên tàu bị thiếu bằng giá trị xuất hiện nhiều nhất (Mode)
df['embarked']=df['embarked'].fillna(df['embarked']. mode()[0])

# LOẠI BỎ CỘT KHÔNG CẦN THIẾT
# Bỏ cột 'deck' (thiếu quá nhiều), 'embark_town' (trùng với 'embarked'), 'alive' (đây là đáp án dạng chữ, ta dùng cột 'survived' dạng số)
df = df.drop(columns=['deck', 'embark_town', 'alive', 'class', 'who', 'adult_male'])

# MÃ HÓA DỮ LIỆU (ENCODING)
# Máy học chỉ hiểu số. Ta cần đổi "male/female" thành 0/1

# Cách 1: Label Encoding (Gán số thủ công cho 2 giá trị)
df['sex'] = df['sex'].map({'male': 0, 'female': 1})

# Cách 2: One-Hot Encoding cho cột 'embarked' (S, C, Q)
# Nó sẽ tạo ra các cột mới: embarked_S, embarked_C, embarked_Q
df = pd.get_dummies(df, columns=['embarked'], drop_first=True)

# Kiểm tra lại dữ liệu sau khi làm sạchj
print("\nDữ liệu sau khi làmsạch (Sẵn sàng training):")
print(df.head())

"""---

### Bước 3: Chia tập dữ liệu (Train/Test Split)

* **Tập Train (Huấn luyện):** Giống như sách giáo khoa để mô hình học.
* **Tập Test (Kiểm tra):** Giống như đề thi. Mô hình chưa bao giờ thấy dữ liệu này. Dùng để đánh giá xem mô hình có học vẹt không.

Tỉ lệ thường dùng: 80% Train - 20% Test.
"""

from sklearn.model_selection import train_test_split

# Xác định đâu là input(X) và đâu là Output cần dự đoán (y)
X = df.drop('survived', axis=1) # Input là tất cả các cột trừ cột survived
y = df['survived']    # Output làcột survived

# Chia dl
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42 )

print(f"Số lượng dòng để train: {X_train.shape[0] }")
print(f"Số lượng dòng để test: {X_test.shape[0]}")

"""---

### Bước 4: Huấn luyện mô hình (Training)

dùng mô hình **Random Forest Classifier**.

* **Ý tưởng:** Hãy tưởng tượng thay vì hỏi 1 chuyên gia, bạn hỏi 100 người bình thường (các cây quyết định - Decision Trees). Mỗi người đưa ra ý kiến, và kết quả cuối cùng là ý kiến đa số. Cách này giúp giảm sai sót.
"""

from sklearn.ensemble import RandomForestClassifier

# Khởi tạo mô hình
# n_estimators=100 nghĩa là tạo ra 100 cây quyết dịnh
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Bắt đầu huấn luyện (học từ dữ liệu tran
print("Đang huấn luyện mô hình...")
model.fit(X_train, y_train)
print( "Huấn luyện hoàn tất")

"""---

### Bước 5: Đánh giá (Evaluation)

Bây giờ ta sẽ cho mô hình làm bài thi (dự đoán trên tập `X_test`) và so sánh với đáp án thật (`y_test`).

**Các chỉ số quan trọng:**

1. **Accuracy (Độ chính xác):** Tổng số câu đúng / Tổng số câu hỏi. (Vd: 80% nghĩa là đoán 10 người thì đúng 8).
2. **Precision (Độ chính xác của dự báo dương):** Trong số những người mô hình bảo là "Sống", bao nhiêu % thực sự sống? (Quan trọng để tránh mừng hụt).
3. **Recall (Độ phủ):** Trong số những người thực sự sống, mô hình tìm ra được bao nhiêu %? (Quan trọng để không bỏ sót ai).
"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Cho mô hình dự đoán thử trên tập test
y_pred = model.predict(X_test)

# 1. Tính Acuracy
acc = accuracy_score(y_test, y_pred)
print(f"\nĐộ chính xác tổng quát (Accuracy): {acc:.2f} (hay {acc*100:.2f}%)")

# 2. bảng bc chi tiết (Precision,Recall, F1-score)
print("\nBáo cáo chi tiết:")
print(classification_report(y_test, y_pred))

# 3. Ma trận nhầm lẫn(Confusionmatrix
print("\nMa trận nhầm lẫn:")
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')
plt.xlabel('Dự đoán của máy')
plt.ylabel('Thực tế')
plt.show()